### ISSUE TITLE
Sysdig Provider uses deprecated module

### ISSUE THREAD

**Issue by marojor** [sysdiglabs/terraform-aws-fargate-orchestrator-agent#5]
Originally reported  here https://github.com/sysdiglabs/terraform-provider-sysdig/issues/182

> The template module has been deprecated for some time:

> https://registry.terraform.io/providers/hashicorp/template/latest/docs

> It's currently required by the sysdig provider which means sysdig's terraform code does not work on Mac M1 (and any other arm64 machines).

> Can you guys please update to use templatefile which is the correct way to do templates these days:

> https://www.terraform.io/language/functions/templatefile

**Comment by skadz** [comment]
It looks like @achandras fixed this.  Can we get a release, so my folks on M1/M2 macs can start working again?

Thanks!

**Comment by achandras** [comment]
Hey @skadz, for some reason the Github release was sitting as a draft, but that's now published.

v0.2.0 of the module was published to the TF registry yesterday after @danhigham's fix and should be available to use!

**Comment by francesco-racciatti** [comment]
This has been released w/ v0.2.0
